/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package threadrelay;

/**
 *
 * @author pasqui.filippo
 */
public class StaffettaForm extends javax.swing.JFrame implements Observer {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(StaffettaForm.class.getName());

    /**
     * Creates new form StaffettaForm
     */
    public StaffettaForm() {
        initComponents();
        this.getContentPane().setBackground(new java.awt.Color(33, 37, 41));

    // Configurazione bar1 (Verde)
    bar1.setForeground(new java.awt.Color(40, 167, 69));
    bar1.setStringPainted(true);
    bar1.setString("Atleta 1: Pronto");

    // Configurazione bar2 (Blu)
    bar2.setForeground(new java.awt.Color(0, 123, 255));
    bar2.setStringPainted(true);
    bar2.setString("Atleta 2: In attesa");

    // Configurazione bar3 (Giallo)
    bar3.setForeground(new java.awt.Color(255, 193, 7));
    bar3.setStringPainted(true);
    bar3.setString("Atleta 3: In attesa");

    // Configurazione bar4 (Rosso)
    bar4.setForeground(new java.awt.Color(220, 53, 69));
    bar4.setStringPainted(true);
    bar4.setString("Atleta 4: In attesa");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bar1 = new javax.swing.JProgressBar();
        bar2 = new javax.swing.JProgressBar();
        bar3 = new javax.swing.JProgressBar();
        btnStart = new javax.swing.JButton();
        bar4 = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnStart.setText("START");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bar4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bar3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bar1, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(btnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(bar1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bar2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bar3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bar4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btnStart)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        IntBox box =new IntBox();
        for(int i=1 ; i<=4; i++){
            AtletaStaffetta a =new AtletaStaffetta(i,box);
            a.addObserver(this);
            a.start();
        }
    }//GEN-LAST:event_btnStartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new StaffettaForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar bar1;
    private javax.swing.JProgressBar bar2;
    private javax.swing.JProgressBar bar3;
    private javax.swing.JProgressBar bar4;
    private javax.swing.JButton btnStart;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(int idAtleta, int progresso) {
        switch (idAtleta){
            case 1:
                bar1.setValue(progresso);
                if(progresso < 100) bar1.setString("Atleta 1: CORRE (" + progresso + "%)");
                else bar1.setString("Atleta 1: FINE");
                break;
            case 2:
                bar2.setValue(progresso);
                if(progresso < 100) bar2.setString("Atleta 2: CORRE (" + progresso + "%)");
                else bar2.setString("Atleta 2: FINE");
                break;
            case 3:
                bar3.setValue(progresso);
                if(progresso < 100) bar3.setString("Atleta 3: CORRE (" + progresso + "%)");
                else bar3.setString("Atleta 3: FINE");
                break;
            case 4:
                bar4.setValue(progresso);
                if(progresso < 100) bar4.setString("Atleta 4: CORRE (" + progresso + "%)");
                else bar4.setString("Atleta 4: FINE");
                break;
            
            
        }
    }
}
