/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package threadrelay;

import java.util.ArrayList;

/**
 *
 * @author pasqui.filippo
 */
public class StaffettaForm extends javax.swing.JFrame implements Observer {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(StaffettaForm.class.getName());
    private IntBox box;
    private ArrayList<AtletaStaffetta> listaAtleti= new ArrayList<>();
    public StaffettaForm() {
        initComponents();
        box=new IntBox();
        this.getContentPane().setBackground(new java.awt.Color(33, 37, 41));

    // Configurazione bar1 (Verde)
    bar1.setForeground(new java.awt.Color(40, 167, 69));
    bar1.setStringPainted(true);
    bar1.setString("Atleta 1: Pronto");

    // Configurazione bar2 (Blu)
    bar2.setForeground(new java.awt.Color(0, 123, 255));
    bar2.setStringPainted(true);
    bar2.setString("Atleta 2: In attesa");

    // Configurazione bar3 (Giallo)
    bar3.setForeground(new java.awt.Color(255, 193, 7));
    bar3.setStringPainted(true);
    bar3.setString("Atleta 3: In attesa");

    // Configurazione bar4 (Rosso)
    bar4.setForeground(new java.awt.Color(220, 53, 69));
    bar4.setStringPainted(true);
    bar4.setString("Atleta 4: In attesa");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bar1 = new javax.swing.JProgressBar();
        bar2 = new javax.swing.JProgressBar();
        bar3 = new javax.swing.JProgressBar();
        btnStart = new javax.swing.JButton();
        bar4 = new javax.swing.JProgressBar();
        btnStop = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(bar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 50, 353, 21));
        getContentPane().add(bar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 83, 353, 22));
        getContentPane().add(bar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 111, 353, 20));

        btnStart.setText("START");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });
        getContentPane().add(btnStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 180, 130, -1));
        getContentPane().add(bar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 143, 353, 21));

        btnStop.setText("STOP");
        btnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopActionPerformed(evt);
            }
        });
        getContentPane().add(btnStop, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 130, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
       btnStart.setEnabled(false);
        listaAtleti.clear();
        bar1.setValue(0);
        bar1.setString("Atleta 1: Pronto");
        bar2.setValue(0);
        bar2.setString("Atleta 2: In attesa");
        bar3.setValue(0);
        bar3.setString("Atleta 3: In attesa");
        bar4.setValue(0);
        bar4.setString("Atleta 4: In attesa");
        box = new IntBox();
        for(int i=1 ; i<=4; i++){
            AtletaStaffetta a =new AtletaStaffetta(i,box);
            a.addObserver(this);
            listaAtleti.add(a);
            a.start();
        }
    }//GEN-LAST:event_btnStartActionPerformed

    private void btnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopActionPerformed
        for(AtletaStaffetta a : listaAtleti){
            a.ferma();
        }
         btnStart.setEnabled(true);
    }//GEN-LAST:event_btnStopActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new StaffettaForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar bar1;
    private javax.swing.JProgressBar bar2;
    private javax.swing.JProgressBar bar3;
    private javax.swing.JProgressBar bar4;
    private javax.swing.JButton btnStart;
    private javax.swing.JButton btnStop;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(int idAtleta, int progresso) {
        switch (idAtleta){
            case 1:
                bar1.setValue(progresso);
                if(progresso < 100) bar1.setString("Atleta 1: CORRE (" + progresso + "%)");
                else bar1.setString("Atleta 1: FINE");
                break;
            case 2:
                bar2.setValue(progresso);
                if(progresso < 100) bar2.setString("Atleta 2: CORRE (" + progresso + "%)");
                else bar2.setString("Atleta 2: FINE");
                break;
            case 3:
                bar3.setValue(progresso);
                if(progresso < 100) bar3.setString("Atleta 3: CORRE (" + progresso + "%)");
                else bar3.setString("Atleta 3: FINE");
                break;
            case 4:
                bar4.setValue(progresso);
                if(progresso < 100) bar4.setString("Atleta 4: CORRE (" + progresso + "%)");
                else bar4.setString("Atleta 4: FINE");
                break;
            
            
        }
    }
}
